// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdProjectTab 100 
#define cmdProjectTab_LabelTitle_RESID 60001
#define cmdGraphicTab 110 
#define cmdGraphicTab_LabelTitle_RESID 60002
#define cmdCsgTab 120 
#define cmdCsgTab_LabelTitle_RESID 60003
#define cmdDatabaseTab 130 
#define cmdDatabaseTab_LabelTitle_RESID 60004
#define cmdMenuNewProject 200 
#define cmdMenuNewProject_LabelTitle_RESID 60005
#define cmdMenuNewProject_LargeImages_RESID 201
#define cmdMenuOpenProject 202 
#define cmdMenuOpenProject_LabelTitle_RESID 60006
#define cmdMenuOpenProject_LargeImages_RESID 203
#define cmdMenuSaveAsProject 204 
#define cmdMenuSaveAsProject_LabelTitle_RESID 60007
#define cmdMenuSaveAsProject_LargeImages_RESID 205
#define cmdMenuSaveProject 206 
#define cmdMenuSaveProject_LabelTitle_RESID 60008
#define cmdMenuSaveProject_LargeImages_RESID 207
#define cmdMenuExit 208 
#define cmdMenuExit_LabelTitle_RESID 60009
#define cmdMenuExit_LargeImages_RESID 209
#define cmdProject 220 
#define cmdProject_LabelTitle_RESID 60010
#define cmdNewProject 221 
#define cmdNewProject_LabelTitle_RESID 60011
#define cmdNewProject_TooltipTitle_RESID 60012
#define cmdNewProject_LargeImages_RESID 222
#define cmdOpenProject 223 
#define cmdOpenProject_LabelTitle_RESID 60013
#define cmdOpenProject_TooltipTitle_RESID 60014
#define cmdOpenProject_SmallImages_RESID 224
#define cmdSaveAsProject 225 
#define cmdSaveAsProject_LabelTitle_RESID 60015
#define cmdSaveAsProject_TooltipTitle_RESID 60016
#define cmdSaveAsProject_SmallImages_RESID 226
#define cmdSaveProject 227 
#define cmdSaveProject_LabelTitle_RESID 60017
#define cmdSaveProject_TooltipTitle_RESID 60018
#define cmdSaveProject_SmallImages_RESID 228
#define cmdShortcuts 240 
#define cmdShortcuts_LabelTitle_RESID 60019
#define cmdShowShortcuts 241 
#define cmdShowShortcuts_LabelTitle_RESID 60020
#define cmdShowShortcuts_TooltipTitle_RESID 60021
#define cmdShowShortcuts_LargeImages_RESID 242
#define cmdLogFile 250 
#define cmdLogFile_LabelTitle_RESID 60022
#define cmdShowLogFile 251 
#define cmdShowLogFile_LabelTitle_RESID 60023
#define cmdShowLogFile_TooltipTitle_RESID 60024
#define cmdShowLogFile_LargeImages_RESID 252
#define cmdObject 300 
#define cmdObject_LabelTitle_RESID 60025
#define cmdObjectType 301 
#define cmdObjectType_LabelTitle_RESID 60026
#define cmdObjectType_LargeImages_RESID 302
#define cmd3Dcube 303 
#define cmd3Dcube_LabelTitle_RESID 60027
#define cmd3Dcube_TooltipTitle_RESID 60028
#define cmd3Dcube_TooltipDescription_RESID 60029
#define cmd3Dcube_LargeImages_RESID 304
#define cmd3Dsphere 305 
#define cmd3Dsphere_LabelTitle_RESID 60030
#define cmd3Dsphere_TooltipTitle_RESID 60031
#define cmd3Dsphere_TooltipDescription_RESID 60032
#define cmd3Dsphere_LargeImages_RESID 306
#define cmd3Dcylinder 307 
#define cmd3Dcylinder_LabelTitle_RESID 60033
#define cmd3Dcylinder_TooltipTitle_RESID 60034
#define cmd3Dcylinder_TooltipDescription_RESID 60035
#define cmd3Dcylinder_LargeImages_RESID 308
#define cmd3Dcone 309 
#define cmd3Dcone_LabelTitle_RESID 60036
#define cmd3Dcone_TooltipTitle_RESID 60037
#define cmd3Dcone_TooltipDescription_RESID 60038
#define cmd3Dcone_LargeImages_RESID 310
#define cmd3Dpyramid 311 
#define cmd3Dpyramid_LabelTitle_RESID 60039
#define cmd3Dpyramid_TooltipTitle_RESID 60040
#define cmd3Dpyramid_TooltipDescription_RESID 60041
#define cmd3Dpyramid_LargeImages_RESID 312
#define cmd3Dtorus 313 
#define cmd3Dtorus_LabelTitle_RESID 60042
#define cmd3Dtorus_TooltipTitle_RESID 60043
#define cmd3Dtorus_TooltipDescription_RESID 60044
#define cmd3Dtorus_LargeImages_RESID 314
#define cmdObjectName 320 
#define cmdObjectName_LabelTitle_RESID 60045
#define cmdObjectName_TooltipTitle_RESID 60046
#define cmdObjectName_TooltipDescription_RESID 60047
#define cmdObjectValues 321 
#define cmdObjectValues_LabelTitle_RESID 60048
#define cmdObjectValues_TooltipTitle_RESID 60049
#define cmdObjectValues_TooltipDescription_RESID 60050
#define cmdObjectAdd 322 
#define cmdObjectAdd_LabelTitle_RESID 60051
#define cmdObjectAdd_TooltipTitle_RESID 60052
#define cmdObjectAdd_LargeImages_RESID 323
#define cmdObjectClone 324 
#define cmdObjectClone_LabelTitle_RESID 60053
#define cmdObjectClone_TooltipTitle_RESID 60054
#define cmdObjectClone_LargeImages_RESID 325
#define cmdObjectDelete 326 
#define cmdObjectDelete_LabelTitle_RESID 60055
#define cmdObjectDelete_TooltipTitle_RESID 60056
#define cmdObjectDelete_LargeImages_RESID 327
#define cmdSceneMode 340 
#define cmdSceneMode_LabelTitle_RESID 60057
#define cmdSceneModeType 341 
#define cmdSceneModeType_LabelTitle_RESID 60058
#define cmdSceneModeType_TooltipTitle_RESID 60059
#define cmdTransformation 350 
#define cmdTransformation_LabelTitle_RESID 60060
#define cmdTransformationType 351 
#define cmdTransformationType_LabelTitle_RESID 60061
#define cmdTransformationType_TooltipTitle_RESID 60062
#define cmdTransformationStep 352 
#define cmdTransformationStep_LabelTitle_RESID 60063
#define cmdTransformationStep_TooltipTitle_RESID 60064
#define cmdTransformationStep_TooltipDescription_RESID 60065
#define cmdTransformationXAxis 353 
#define cmdTransformationXAxis_LabelTitle_RESID 60066
#define cmdTransformationXAxis_TooltipTitle_RESID 60067
#define cmdTransformationXAxis_LargeImages_RESID 354
#define cmdTransformationYAxis 355 
#define cmdTransformationYAxis_LabelTitle_RESID 60068
#define cmdTransformationYAxis_TooltipTitle_RESID 60069
#define cmdTransformationYAxis_LargeImages_RESID 356
#define cmdTransformationZAxis 357 
#define cmdTransformationZAxis_LabelTitle_RESID 60070
#define cmdTransformationZAxis_TooltipTitle_RESID 60071
#define cmdTransformationZAxis_LargeImages_RESID 358
#define cmdLight 370 
#define cmdLight_LabelTitle_RESID 60072
#define cmdLightMaterial 371 
#define cmdLightMaterial_LabelTitle_RESID 60073
#define cmdLightMaterial_LargeImages_RESID 372
#define cmdAmbientLight 373 
#define cmdAmbientLight_LabelTitle_RESID 60074
#define cmdDiffuseLight 374 
#define cmdDiffuseLight_LabelTitle_RESID 60075
#define cmdSpecularLight 375 
#define cmdSpecularLight_LabelTitle_RESID 60076
#define cmdAmbientMaterial 376 
#define cmdAmbientMaterial_LabelTitle_RESID 60077
#define cmdDiffuseMaterial 377 
#define cmdDiffuseMaterial_LabelTitle_RESID 60078
#define cmdSpecularMaterial 378 
#define cmdSpecularMaterial_LabelTitle_RESID 60079
#define cmdEmissiveMaterial 379 
#define cmdEmissiveMaterial_LabelTitle_RESID 60080
#define cmdLightMaterialValues 380 
#define cmdLightMaterialValues_LabelTitle_RESID 60081
#define cmdLightMaterialValues_TooltipTitle_RESID 60082
#define cmdLightPosition 381 
#define cmdLightPosition_LabelTitle_RESID 60083
#define cmdLightSource 382 
#define cmdLightSource_LabelTitle_RESID 60084
#define cmdTexture 390 
#define cmdTexture_LabelTitle_RESID 60085
#define cmdTextureAdd 391 
#define cmdTextureAdd_LabelTitle_RESID 60086
#define cmdTextureAdd_LargeImages_RESID 392
#define cmdShow 395 
#define cmdShow_LabelTitle_RESID 60087
#define cmdShowAxis  396 
#define cmdShowAxis_LabelTitle_RESID 60088
#define cmdShowGrid  397 
#define cmdShowGrid_LabelTitle_RESID 60089
#define cmdCsgTree 500 
#define cmdCsgTree_LabelTitle_RESID 60090
#define cmdCsgTreeNames 501 
#define cmdCsgTreeNames_LabelTitle_RESID 60091
#define cmdCsgTreeNodes 502 
#define cmdCsgTreeNodes_LabelTitle_RESID 60092
#define cmdNodeAdd 503 
#define cmdNodeAdd_LabelTitle_RESID 60093
#define cmdNodeAdd_TooltipTitle_RESID 60094
#define cmdNodeAdd_LargeImages_RESID 504
#define cmdNodeRemove 505 
#define cmdNodeRemove_LabelTitle_RESID 60095
#define cmdNodeRemove_TooltipTitle_RESID 60096
#define cmdNodeRemove_LargeImages_RESID 506
#define cmdTreeDelete 507 
#define cmdTreeDelete_LabelTitle_RESID 60097
#define cmdTreeDelete_TooltipTitle_RESID 60098
#define cmdTreeDelete_LargeImages_RESID 508
#define cmdBoolOperation 520 
#define cmdBoolOperation_LabelTitle_RESID 60099
#define cmdSubtraction 521 
#define cmdSubtraction_LabelTitle_RESID 60100
#define cmdSubtraction_LargeImages_RESID 522
#define cmdIntersection 523 
#define cmdIntersection_LabelTitle_RESID 60101
#define cmdIntersection_LargeImages_RESID 524
#define cmdUnion 525 
#define cmdUnion_LabelTitle_RESID 60102
#define cmdUnion_LargeImages_RESID 526
#define cmdCsgCalculation 540 
#define cmdCsgCalculation_LabelTitle_RESID 60103
#define cmdCsgCalculate 541 
#define cmdCsgCalculate_LabelTitle_RESID 60104
#define cmdCsgCalculate_LargeImages_RESID 542
#define cmdOpenCsg 550 
#define cmdOpenCsg_LabelTitle_RESID 60105
#define cmdCsgAlgorithm 551 
#define cmdCsgAlgorithm_LabelTitle_RESID 60106
#define cmdCsgAlgorithm_LargeImages_RESID 552
#define cmdAutomatic 553 
#define cmdAutomatic_LabelTitle_RESID 60107
#define cmdSCS 554 
#define cmdSCS_LabelTitle_RESID 60108
#define cmdGoldfeather 555 
#define cmdGoldfeather_LabelTitle_RESID 60109
#define cmdDepthAlgorithm 556 
#define cmdDepthAlgorithm_LabelTitle_RESID 60110
#define cmdNoDepthComplexitySampling 557 
#define cmdNoDepthComplexitySampling_LabelTitle_RESID 60111
#define cmdOcclusionQuery 558 
#define cmdOcclusionQuery_LabelTitle_RESID 60112
#define cmdDepthComplexitySampling 559 
#define cmdDepthComplexitySampling_LabelTitle_RESID 60113
#define cmdOffscreenType 560 
#define cmdOffscreenType_LabelTitle_RESID 60114
#define cmdAutomaticOffscreenType 561 
#define cmdAutomaticOffscreenType_LabelTitle_RESID 60115
#define cmdFrameBufferObject 562 
#define cmdFrameBufferObject_LabelTitle_RESID 60116
#define cmdPBuffer 563 
#define cmdPBuffer_LabelTitle_RESID 60117
#define cmdFrameBufferObjectARB 564 
#define cmdFrameBufferObjectARB_LabelTitle_RESID 60118
#define cmdFrameBufferObjectEXT 565 
#define cmdFrameBufferObjectEXT_LabelTitle_RESID 60119
#define cmdOptimization 566 
#define cmdOptimization_LabelTitle_RESID 60120
#define cmdOptimizationDefault 567 
#define cmdOptimizationDefault_LabelTitle_RESID 60121
#define cmdOptimizationOff 568 
#define cmdOptimizationOff_LabelTitle_RESID 60122
#define cmdOptimizationOn 569 
#define cmdOptimizationOn_LabelTitle_RESID 60123
#define cmdDatabase 700 
#define cmdDatabase_LabelTitle_RESID 60124
#define cmdDatabaseConnect 701 
#define cmdDatabaseConnect_LabelTitle_RESID 60125
#define cmdDatabaseConnect_TooltipTitle_RESID 60126
#define cmdDatabaseConnect_LargeImages_RESID 702
#define cmdDatabaseDisconnect 703 
#define cmdDatabaseDisconnect_LabelTitle_RESID 60127
#define cmdDatabaseDisconnect_TooltipTitle_RESID 60128
#define cmdDatabaseDisconnect_LargeImages_RESID 704
#define cmdDatabaseProjects 710 
#define cmdDatabaseProjects_LabelTitle_RESID 60129
#define cmdDatabaseUpload 711 
#define cmdDatabaseUpload_LabelTitle_RESID 60130
#define cmdDatabaseUpload_TooltipTitle_RESID 60131
#define cmdDatabaseUpload_LargeImages_RESID 712
#define cmdDatabaseDownload 713 
#define cmdDatabaseDownload_LabelTitle_RESID 60132
#define cmdDatabaseDownload_TooltipTitle_RESID 60133
#define cmdDatabaseDownload_LargeImages_RESID 714
#define cmdProjectsList 715 
#define cmdProjectsList_LabelTitle_RESID 60134
#define cmdProjectsList_TooltipTitle_RESID 60135
#define cmdHelp 800 
#define InternalCmd2_LabelTitle_RESID 60136
